### ISSUE TITLE
Needing a user/pass to download

### ISSUE THREAD

**Issue by mibalas** [TerraMA2/terrama2#1065]
What's the user/pass to download terrama2-3rdparty-linux-ubuntu-14.04.tar.gz ?

**Comment by janosimas** [comment]
The  terrama2-3rdparty-linux-ubuntu-14.04.tar.gz is highly outdated, this command should install almost everything you need:

`
sudo apt-get install cmake build-essential libcurl3-dev libpython2.7-dev libquazip0-dev libproj-dev libgeos++-dev libxerces-c-dev
`
You'll also need the VMime library:
https://github.com/kisli/vmime

to run the unittest you also need the google mock:
https://github.com/google/googletest

We are preparing the deb package that should be released with the beta3 version.

**Comment by janosimas** [comment]
To use the WebApplication follow the instructions:
[webapp/README.md](https://github.com/TerraMA2/terrama2/blob/master/webapp/README.md)

**Comment by mibalas** [comment]
I tried to install the webapp and so many errors occurred:
`npm install -g bower`
`npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.`
`/usr/local/bin/bower-> /usr/local/lib/node_modules/bower/bin/bower`
`bower@1.8.0 /usr/local/lib/node_modules/bower
`


`npm install`
`npm ERR! install Couldn't read dependencies`
`npm ERR! Linux 3.13.0-46-generic`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"`
`npm ERR! node v4.2.6`
`npm ERR! npm  v2.14.12`
`npm ERR! path /home/terrama2/codebase/package.json`
`npm ERR! code ENOPACKAGEJSON`
`npm ERR! errno -2`
`npm ERR! syscall open`
`npm ERR! package.json ENOENT: no such file or directory, open` `'/home/terrama2/codebase/package.json'`
`npm ERR! package.json This is most likely not a problem with npm itself.`
`npm ERR! package.json npm can't find a package.json file in your current directory.`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     /home/terrama2/codebase/npm-debug.log`


` bower install`
`bower ESUDO         Cannot be run with sudo`
`Additional error details:`
`Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.
http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814
You can however run a command with sudo using --allow-root option`

`grunt`
`grunt-cli: The grunt command line interface (v1.2.0)`
`Fatal error: Unable to find local grunt.
`

I'm using Ubuntu Server 14.04.

**Comment by janosimas** [comment]
first, I missed one dependency: [Terralib](http://www.dpi.inpe.br/terralib5/wiki/doku.php?id=wiki:downloads)

now, your problem, the **npm** and **bower** commands should be run at the **webapp** folder.

**Comment by janosimas** [comment]
@mibalas I updated the [Wiki](https://github.com/TerraMA2/terrama2/wiki/Installation) installation document.

See if it helps.

**Comment by mibalas** [comment]
Hello, I followed the new tutorial but I get the errors below when I tap the command **npm start** in webapp folder:

/home/terrama2/codebase/webapp/node_modules/bcrypt/node_modules/bindings/binding                                                 s.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/terrama2/codebase/webapp/node_modules/bcrypt/node_modules                                                 /bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/terrama2/codebase/webapp/node_modules/bcrypt/bc                                                 rypt.js:3:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/terrama2/codebase/webapp/core/Utils.js:18:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! terrama2-webapp@4.0.0-beta2 start: `grunt && node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terrama2-webapp@4.0.0-beta2 start script 'grunt && node .                                                 /bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the terrama2-webapp packa                                                 ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt && node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs terrama2-webapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls terrama2-webapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/terrama2/codebase/webapp/npm-debug.log

**Comment by jeansouza** [comment]
@mibalas please, check the version of your node.js, you can do that executing the following command:

**nodejs -v**

**Comment by mibalas** [comment]
I was using nodejs v 6.11. 
I uninstalled that and install nodejs v4.8 (following the tutorial) but npm was not installed :(

**Comment by jeansouza** [comment]
Uninstall nodejs, and try again with nodejs v4. Something went wrong with your installation, because you should had npm installed. After installing node and npm, delete the node_modules folder (from the webapp root) and execute npm install again.

**Comment by mibalas** [comment]
I tried to reinstall but npm did not install using apt-get, so I manually installed (downloaded v4.8 and make install).
Now I have nodejs 4.8.3 and npm 2.15.11 but the same errors are occurring when I try npm start:

[11:41:21] error (bin/www:181) Error: getaddrinfo ENOTFOUND registro registro:5432

npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! terrama2-webapp@4.0.0-beta2 start: `grunt && node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terrama2-webapp@4.0.0-beta2 start script 'grunt && node ./bin/www'.
npm ERR! This is most likely a problem with the terrama2-webapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt && node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs terrama2-webapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls terrama2-webapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/terrama2/codebase/webapp/npm-debug.log

**Comment by janosimas** [comment]
Did you configure your Postgres? Looks like the webapp can't connect.
You should configure a password to you [postgres](https://github.com/TerraMA2/terrama2/wiki/Installation#postgresql).

And set the same password in the [config](https://github.com/TerraMA2/terrama2/wiki/Installation#terrama2-configure-file) file.

**Comment by mibalas** [comment]
Hi, I already did that but without success..

However, I started a new Ubuntu Server 14 on a virtual machine and followed the tutorial step by step, the npm start command presented some errors but it worked!

Now i'm acessing the TerraMA.

The errors are:
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.3
npm ERR! npm  v2.15.11
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

Can these errors interfere with program behavior?


Is there any tutorial on how to operate and configure the system?

**Comment by janosimas** [comment]
@mibalas This is still a beta version, we are writing a user manual. I wrote the installation guide in the wiki while we don't have a more complete manual.

What are you calling  "accessing the TerraMA"? what are the commands you are using? in which folder?
The user interface is a web interface, if the npm start didn't work you won't be able to access.

**Comment by mibalas** [comment]
When I tap 'npm start' in TERRAMA2-SRC/webapp folder, it starts (with the errors reported above), but I can access via browser (localhost:36000) and login.
But I dont know how to configure projects and services dont start

![terrama2](https://user-images.githubusercontent.com/15907968/27796866-e25bed86-5fe1-11e7-8618-f2aebb92cd40.png)

I'm trying to configure a project now and add some data.

**Comment by janosimas** [comment]
Ok, I'll close this issue and will create a little 'how to use' at the wiki.

Give me a couple of days.


ps: we made some changes recently, if you compile and install (`make install`) I'll install and configure the `pm2`. This way the webapp will run automatically.

**Comment by janosimas** [comment]
@mibalas sorry for not updating you. We are on a tight schedule. :-/
